{"name": "Login with wrong password", "status": "broken", "statusDetails": {"message": "SystemExit: Testing failed in login with credentials : kamelmohsenkamel@gmail.com & wrong_password", "trace": "self = <Web_Testing.Pages.login.LoginPage object at 0x000002914FCC0E48>, email = 'kamelmohsenkamel@gmail.com', password = 'wrong_password'\n\n    def login_to_spotify(self, email, password):\n        # timeout for login\n        timeout = 5\n        try:\n>           self.clear_credentials() # clear email and password fields\n\nPages\\login.py:93: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <Web_Testing.Pages.login.LoginPage object at 0x000002914FCC0E48>\n\n    def clear_credentials(self):\n>       self.email_txt.clear()\nE       AttributeError: 'NoneType' object has no attribute 'clear'\n\nPages\\login.py:46: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <Web_Testing.Tests.test_signin.TestLogin object at 0x000002914FCAED88>, setup = None\n\n    @allure.severity(allure.severity_level.BLOCKER)\n    @allure.story(\"Failing login\")\n    @allure.sub_suite(\"Login with wrong password\")\n    @allure.title(\"Login with wrong password\")\n    @allure.description(\"Signing in with the following credentials email : kamelmohsenkamel@gmail.com & password: wrong password\")\n    @pytest.mark.Do\n    @pytest.mark.Login\n    def test_case_2(self, setup):\n        logged_out_page = LoggedOutHome(self.driver)\n        logged_out_page.tb_login_btn.click()\n        lp = LoginPage(self.driver)\n        lp.check_login_page()\n        time.sleep(3)\n>       if lp.login_to_spotify(\"kamelmohsenkamel@gmail.com\", \"wrong_password\"):\n\nTests\\test_signin.py:73: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nPages\\login.py:133: in login_to_spotify\n    exit('Testing failed in login with credentials : ' + email + \" & \" + password)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = Use exit() or Ctrl-Z plus Return to exit, code = 'Testing failed in login with credentials : kamelmohsenkamel@gmail.com & wrong_password'\n\n    def __call__(self, code=None):\n        # Shells like IDLE catch the SystemExit, but listen when their\n        # stdin wrapper is closed.\n        try:\n            sys.stdin.close()\n        except:\n            pass\n>       raise SystemExit(code)\nE       SystemExit: Testing failed in login with credentials : kamelmohsenkamel@gmail.com & wrong_password\n\nC:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\\lib\\_sitebuiltins.py:26: SystemExit"}, "description": "Signing in with the following credentials email : kamelmohsenkamel@gmail.com & password: wrong password", "start": 1584338015111, "stop": 1584338019648, "uuid": "525dc4c3-693e-4b83-8000-11bedfc6b31b", "historyId": "b85f51a1b4fd93617a90ce9879e3d694", "testCaseId": "d7554bc16a6a460267040e285ac930f6", "fullName": "Tests.test_signin.TestLogin#test_case_2", "labels": [{"name": "story", "value": "Failing login"}, {"name": "suite", "value": "Login Tests"}, {"name": "severity", "value": "blocker"}, {"name": "parentSuite", "value": "End to End testing"}, {"name": "feature", "value": "Log in Tests"}, {"name": "subSuite", "value": "Login with wrong password"}, {"name": "tag", "value": "Do"}, {"name": "tag", "value": "Login"}, {"name": "host", "value": "DESKTOP-1RVKD4K"}, {"name": "thread", "value": "4440-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_signin"}]}