{"uuid": "d50d2747-b4ce-48cc-9e66-d3ce6c93f15a", "children": ["27d178be-d95c-4249-aeab-5f8178e46d8b"], "befores": [{"name": "setup_initial", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status\nfrom unknown error: cannot determine loading status\nfrom disconnected: Unable to receive message from renderer\n  (Session info: chrome=80.0.3987.163)\n\n", "trace": "  File \"/Users/KIMO/Desktop/Testing/venv/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/KIMO/Desktop/Testing/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 958, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/KIMO/Desktop/Testing/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 784, in call_fixture_func\n    res = next(it)\n  File \"/Users/KIMO/Desktop/Testing/Web_Testing/Tests/test_playlist.py\", line 47, in setup_initial\n    self.driver.get(self.helper.get_login_url())\n  File \"/Users/KIMO/Desktop/Testing/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"/Users/KIMO/Desktop/Testing/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/KIMO/Desktop/Testing/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1586743539330, "stop": 1586743540724}], "start": 1586743539330, "stop": 1586743540870}