{"name": "Login with wrong email", "status": "broken", "statusDetails": {"message": "TypeError: 'bool' object is not callable", "trace": "self = <Tests.login_tests.Test object at 0x000001C1A47111C8>, setup_final = None\n\n    @allure.severity(allure.severity_level.BLOCKER)\n    @allure.story(\"Failing login\")\n    @allure.sub_suite(\"Login with wrong email\")\n    @allure.title(\"Login with wrong email\")\n    @allure.description(\"Signing in with the following credentials email : kamelmohsenkamel & password: Kimo2010\")\n    @pytest.mark.Do\n    @pytest.mark.Login\n    def test_case_3(self, setup_final):\n        lp = LoginPage(self.driver)\n        lp.check_login_page()\n>       if lp.login_to_spotify(\"kamelmohsenkamel\", \"Kimo2010\"):\n\nTests\\login_tests.py:87: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nPages\\login.py:79: in login_to_spotify\n    WebDriverWait(self.driver, 10).until(self.check_login_page(), \"Wait to load\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"22109864596030c1accf5b4fdc16e836\")>, method = True, message = 'Wait to load'\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value is not False.\"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n>               value = method(self._driver)\nE               TypeError: 'bool' object is not callable\n\n..\\..\\..\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\selenium\\webdriver\\support\\wait.py:71: TypeError"}, "description": "Signing in with the following credentials email : kamelmohsenkamel & password: Kimo2010", "start": 1583932357147, "stop": 1583932357154, "uuid": "84370db4-f3db-4b39-ad3c-d4e8ba852690", "historyId": "25740cfebdb12bf5b1811f33adb157c7", "testCaseId": "394012d8fa57dbae71ee9d861bcf379b", "fullName": "Tests.login_tests.Test#test_case_3", "labels": [{"name": "parentSuite", "value": "End to End testing"}, {"name": "feature", "value": "Log in Tests"}, {"name": "suite", "value": "Login Tests"}, {"name": "story", "value": "Failing login"}, {"name": "severity", "value": "blocker"}, {"name": "subSuite", "value": "Login with wrong email"}, {"name": "tag", "value": "Do"}, {"name": "tag", "value": "Login"}, {"name": "host", "value": "DESKTOP-1RVKD4K"}, {"name": "thread", "value": "13704-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.login_tests"}]}