{"name": "Login with wrong password", "status": "broken", "statusDetails": {"message": "TypeError: find_element() argument after * must be an iterable, not WebElement", "trace": "self = <Tests.login_tests.Test object at 0x000001CD076E0C48>, setup = None\n\n    @allure.severity(allure.severity_level.BLOCKER)\n    @allure.story(\"Failing login\")\n    @allure.sub_suite(\"Login with wrong password\")\n    @allure.title(\"Login with wrong password\")\n    @allure.description(\"Signing in with the following credentials email : kamelmohsenkamel@gmail.com & password: wrong password\")\n    @pytest.mark.Do\n    @pytest.mark.Login\n    def test_case_2(self, setup):\n        lp = LoginPage(self.driver)\n        lp.check_login_page()\n>       if lp.login_to_spotify(\"kamelmohsenkamel@gmail.com\", \"wrong password\"):\n\nTests\\login_tests.py:68: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nPages\\login.py:79: in login_to_spotify\n    WebDriverWait(self.driver, 10).until(cond.element_to_be_clickable(self.driver.find_element_by_xpath(self.spotify_logo)), \"Wait to load\")\n..\\..\\..\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\selenium\\webdriver\\support\\wait.py:71: in until\n    value = method(self._driver)\n..\\..\\..\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:297: in __call__\n    element = visibility_of_element_located(self.locator)(driver)\n..\\..\\..\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:128: in __call__\n    return _element_if_visible(_find_element(driver, self.locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"9d208f4ae6a75b998dca2f70f5759f16\")>\nby = <selenium.webdriver.remote.webelement.WebElement (session=\"9d208f4ae6a75b998dca2f70f5759f16\", element=\"c5bd89b2-8946-40dd-b3eb-0142eb2b4b74\")>\n\n    def _find_element(driver, by):\n        \"\"\"Looks up an element. Logs and re-raises ``WebDriverException``\n        if thrown.\"\"\"\n        try:\n>           return driver.find_element(*by)\nE           TypeError: find_element() argument after * must be an iterable, not WebElement\n\n..\\..\\..\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:411: TypeError"}, "description": "Signing in with the following credentials email : kamelmohsenkamel@gmail.com & password: wrong password", "start": 1583932736913, "stop": 1583932736926, "uuid": "55814f78-f9e2-4188-90ee-7b2396827a3d", "historyId": "9002a5477b70c2d2732bd4879bd4c9b3", "testCaseId": "5849ff08927baae0bfe7bd1d291d6dac", "fullName": "Tests.login_tests.Test#test_case_2", "labels": [{"name": "severity", "value": "blocker"}, {"name": "subSuite", "value": "Login with wrong password"}, {"name": "suite", "value": "Login Tests"}, {"name": "story", "value": "Failing login"}, {"name": "parentSuite", "value": "End to End testing"}, {"name": "feature", "value": "Log in Tests"}, {"name": "tag", "value": "Do"}, {"name": "tag", "value": "Login"}, {"name": "host", "value": "DESKTOP-1RVKD4K"}, {"name": "thread", "value": "22380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.login_tests"}]}