{"name": "Login with wrong password", "status": "broken", "statusDetails": {"message": "TypeError: 'NoneType' object is not callable", "trace": "self = <Tests.login_tests.Test object at 0x000001DA132EAA88>, setup = None\n\n    @allure.severity(allure.severity_level.BLOCKER)\n    @allure.story(\"Failing login\")\n    @allure.sub_suite(\"Login with wrong password\")\n    @allure.title(\"Login with wrong password\")\n    @allure.description(\"Signing in with the following credentials email : kamelmohsenkamel@gmail.com & password: wrong password\")\n    @pytest.mark.Do\n    @pytest.mark.Login\n    def test_case_2(self, setup):\n        lp = LoginPage(self.driver)\n        lp.check_login_page()\n>       if lp.login_to_spotify(\"kamelmohsenkamel@gmail.com\", \"wrong password\"):\n\nTests\\login_tests.py:68: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nPages\\login.py:79: in login_to_spotify\n    WebDriverWait(self.driver, 10).until(self.check_login_page())\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"807b23400b69ea33bda061b9f320c4d0\")>, method = None, message = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value is not False.\"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n>               value = method(self._driver)\nE               TypeError: 'NoneType' object is not callable\n\n..\\..\\..\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\selenium\\webdriver\\support\\wait.py:71: TypeError"}, "description": "Signing in with the following credentials email : kamelmohsenkamel@gmail.com & password: wrong password", "start": 1583932251840, "stop": 1583932251848, "uuid": "f227ea6e-2717-4bc8-bdaf-38c32d4a5141", "historyId": "9002a5477b70c2d2732bd4879bd4c9b3", "testCaseId": "5849ff08927baae0bfe7bd1d291d6dac", "fullName": "Tests.login_tests.Test#test_case_2", "labels": [{"name": "suite", "value": "Login Tests"}, {"name": "feature", "value": "Log in Tests"}, {"name": "severity", "value": "blocker"}, {"name": "parentSuite", "value": "End to End testing"}, {"name": "story", "value": "Failing login"}, {"name": "subSuite", "value": "Login with wrong password"}, {"name": "tag", "value": "Login"}, {"name": "tag", "value": "Do"}, {"name": "host", "value": "DESKTOP-1RVKD4K"}, {"name": "thread", "value": "11292-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.login_tests"}]}