{"name": "Login with wrong email", "status": "broken", "statusDetails": {"message": "TypeError: find_element() argument after * must be an iterable, not WebElement", "trace": "self = <Tests.login_tests.Test object at 0x000001CD07752F88>, setup_final = None\n\n    @allure.severity(allure.severity_level.BLOCKER)\n    @allure.story(\"Failing login\")\n    @allure.sub_suite(\"Login with wrong email\")\n    @allure.title(\"Login with wrong email\")\n    @allure.description(\"Signing in with the following credentials email : kamelmohsenkamel & password: Kimo2010\")\n    @pytest.mark.Do\n    @pytest.mark.Login\n    def test_case_3(self, setup_final):\n        lp = LoginPage(self.driver)\n        lp.check_login_page()\n>       if lp.login_to_spotify(\"kamelmohsenkamel\", \"Kimo2010\"):\n\nTests\\login_tests.py:87: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nPages\\login.py:79: in login_to_spotify\n    WebDriverWait(self.driver, 10).until(cond.element_to_be_clickable(self.driver.find_element_by_xpath(self.spotify_logo)), \"Wait to load\")\n..\\..\\..\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\selenium\\webdriver\\support\\wait.py:71: in until\n    value = method(self._driver)\n..\\..\\..\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:297: in __call__\n    element = visibility_of_element_located(self.locator)(driver)\n..\\..\\..\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:128: in __call__\n    return _element_if_visible(_find_element(driver, self.locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"9d208f4ae6a75b998dca2f70f5759f16\")>\nby = <selenium.webdriver.remote.webelement.WebElement (session=\"9d208f4ae6a75b998dca2f70f5759f16\", element=\"2aef254c-6f2a-4378-a882-074cbc6ead2b\")>\n\n    def _find_element(driver, by):\n        \"\"\"Looks up an element. Logs and re-raises ``WebDriverException``\n        if thrown.\"\"\"\n        try:\n>           return driver.find_element(*by)\nE           TypeError: find_element() argument after * must be an iterable, not WebElement\n\n..\\..\\..\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:411: TypeError"}, "description": "Signing in with the following credentials email : kamelmohsenkamel & password: Kimo2010", "start": 1583932740114, "stop": 1583932740126, "uuid": "7a7252b8-7590-47ff-a9c7-c82908728acf", "historyId": "25740cfebdb12bf5b1811f33adb157c7", "testCaseId": "394012d8fa57dbae71ee9d861bcf379b", "fullName": "Tests.login_tests.Test#test_case_3", "labels": [{"name": "severity", "value": "blocker"}, {"name": "subSuite", "value": "Login with wrong email"}, {"name": "suite", "value": "Login Tests"}, {"name": "story", "value": "Failing login"}, {"name": "parentSuite", "value": "End to End testing"}, {"name": "feature", "value": "Log in Tests"}, {"name": "tag", "value": "Do"}, {"name": "tag", "value": "Login"}, {"name": "host", "value": "DESKTOP-1RVKD4K"}, {"name": "thread", "value": "22380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.login_tests"}]}